### ISSUE TITLE
Request for Correction: Missing Method Implementation `func (aof *Aof) Read(fn func(value Value)) error` in the Book

### ISSUE THREAD

**Issue by horw** [ahmedash95/build-redis-from-scratch-site#14]
Hi, I appreciate your example, it's great! But it would be nice if you could fix the implementation of `func (aof *Aof) Read(fn func(value Value)) error` in the book.
https://github.com/ahmedash95/build-redis-from-scratch-site/blob/098512759f2116e552ba2800e8d922dbd4f668c5/src/content/docs/en/aof.mdx#L240

**Comment by oshosanya** [comment]
Here is a PR I made to add it in to the page. I hope he merges it soon

https://github.com/ahmedash95/build-redis-from-scratch-site/pull/18

**Comment by ahmedash95** [comment]
The PR got merged. Thanks for reporting it!
